### ISSUE TITLE
Question about deploy

### ISSUE THREAD

**Issue by viniciuspsw** [bitkidd/adonis-starter#3]
Hi there. It's not an issue, just a question. How do you deal with `.env` with dokku? I mean, how do you create the `.env` file when deploying?

**Comment by bitkidd** [comment]
Just use `dokku config:set <your app slug> ENV_SILENT=true DB_DATABASE=<your db database name> DB_USERNAME=<your db username>` plus all other values that you need, just append them to the string. Take a look into [dokku docs](http://dokku.viewdocs.io/dokku~v0.19.13/configuration/environment-variables/) for more info.
